USE QuanLyVatTuXayDung;

-- 1. Bảng tài khoản
CREATE TABLE TAI_KHOAN
(
    MaTK VARCHAR(10) NOT NULL,
    TenDangNhap VARCHAR(50) NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    VaiTro NVARCHAR(30) NOT NULL,
    TrangThai BIT NOT NULL,

    CONSTRAINT PK_TAI_KHOAN PRIMARY KEY (MaTK),
    CONSTRAINT UQ_TAI_KHOAN_TENDANGNHAP UNIQUE (TenDangNhap)
);

-- 2. Bảng loại vật tư
CREATE TABLE LOAI_VAT_TU
(
    MaLoai VARCHAR(10) NOT NULL,
    TenLoai NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255),

    CONSTRAINT PK_LOAI_VAT_TU PRIMARY KEY (MaLoai)
);

-- 3. Bảng vật tư
CREATE TABLE VAT_TU
(
    MaVT VARCHAR(10) NOT NULL,
    TenVT NVARCHAR(150) NOT NULL,
    MaLoai VARCHAR(10) NOT NULL,
    DonViTinh NVARCHAR(30) NOT NULL,
    TonToiThieu DECIMAL(18,2) NOT NULL,
    MoTa NVARCHAR(255),
    TrangThai BIT NOT NULL,

    CONSTRAINT PK_VAT_TU PRIMARY KEY (MaVT),

    CONSTRAINT FK_VAT_TU_LOAI
        FOREIGN KEY (MaLoai) REFERENCES LOAI_VAT_TU(MaLoai)
);

-- 4. Bảng nhà cung cấp
CREATE TABLE NHA_CUNG_CAP
(
    MaNCC VARCHAR(10) NOT NULL,
    TenNCC NVARCHAR(150) NOT NULL,
    DiaChi NVARCHAR(255),
    SoDienThoai VARCHAR(20),
    Email VARCHAR(100),
    TrangThai BIT NOT NULL,

    CONSTRAINT PK_NHA_CUNG_CAP PRIMARY KEY (MaNCC)
);

-- 5. Bảng kho
CREATE TABLE KHO
(
    MaKho VARCHAR(10) NOT NULL,
    TenKho NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255),
    MoTa NVARCHAR(255),
    TrangThai BIT NOT NULL,

    CONSTRAINT PK_KHO PRIMARY KEY (MaKho)
);

-- 6. Bảng công trình
CREATE TABLE CONG_TRINH
(
    MaCT VARCHAR(10) NOT NULL,
    TenCT NVARCHAR(150) NOT NULL,
    DiaDiem NVARCHAR(255) NOT NULL,
    NgayBatDau DATE,
    NgayKetThucDuKien DATE,
    TrangThai VARCHAR(30) NOT NULL,

    CONSTRAINT PK_CONG_TRINH PRIMARY KEY (MaCT)
);

-- 7. Bảng tồn kho
CREATE TABLE TON_KHO
(
    MaKho VARCHAR(10) NOT NULL,
    MaVT VARCHAR(10) NOT NULL,
    SoLuongTon DECIMAL(18,2) NOT NULL,

    CONSTRAINT PK_TON_KHO PRIMARY KEY (MaKho, MaVT),

    CONSTRAINT FK_TON_KHO_KHO
        FOREIGN KEY (MaKho) REFERENCES KHO(MaKho),

    CONSTRAINT FK_TON_KHO_VAT_TU
        FOREIGN KEY (MaVT) REFERENCES VAT_TU(MaVT)
);

-- 8. Bảng phiếu nhập
CREATE TABLE PHIEU_NHAP
(
    MaPN VARCHAR(10) NOT NULL,
    MaNCC VARCHAR(10) NOT NULL,
    MaKho VARCHAR(10) NOT NULL,
    NgayNhap DATETIME NOT NULL,
    NguoiLap VARCHAR(10) NOT NULL,
    GhiChu NVARCHAR(500),
    TrangThai VARCHAR(20) NOT NULL,

    CONSTRAINT PK_PHIEU_NHAP PRIMARY KEY (MaPN),

    CONSTRAINT FK_PHIEU_NHAP_NCC
        FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC),

    CONSTRAINT FK_PHIEU_NHAP_KHO
        FOREIGN KEY (MaKho) REFERENCES KHO(MaKho),

    CONSTRAINT FK_PHIEU_NHAP_TAI_KHOAN
        FOREIGN KEY (NguoiLap) REFERENCES TAI_KHOAN(MaTK)
);

-- 9. Bảng chi tiết phiếu nhập
CREATE TABLE CT_PHIEU_NHAP
(
    MaPN VARCHAR(10) NOT NULL,
    MaVT VARCHAR(10) NOT NULL,
    SoLuong DECIMAL(18,2) NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,

    CONSTRAINT PK_CT_PHIEU_NHAP PRIMARY KEY (MaPN, MaVT),

    CONSTRAINT FK_CT_NHAP_PHIEU_NHAP
        FOREIGN KEY (MaPN) REFERENCES PHIEU_NHAP(MaPN),

    CONSTRAINT FK_CT_NHAP_VAT_TU
        FOREIGN KEY (MaVT) REFERENCES VAT_TU(MaVT)
);

-- 10. Bảng phiếu xuất
CREATE TABLE PHIEU_XUAT
(
    MaPX VARCHAR(10) NOT NULL,
    MaKho VARCHAR(10) NOT NULL,
    MaCT VARCHAR(10) NOT NULL,
    NgayXuat DATETIME NOT NULL,
    NguoiLap VARCHAR(10) NOT NULL,
    GhiChu NVARCHAR(500),
    TrangThai VARCHAR(20) NOT NULL,

    CONSTRAINT PK_PHIEU_XUAT PRIMARY KEY (MaPX),

    CONSTRAINT FK_PHIEU_XUAT_KHO
        FOREIGN KEY (MaKho) REFERENCES KHO(MaKho),

    CONSTRAINT FK_PHIEU_XUAT_CONG_TRINH
        FOREIGN KEY (MaCT) REFERENCES CONG_TRINH(MaCT),

    CONSTRAINT FK_PHIEU_XUAT_TAI_KHOAN
        FOREIGN KEY (NguoiLap) REFERENCES TAI_KHOAN(MaTK)
);

-- 11. Bảng chi tiết phiếu xuất
CREATE TABLE CT_PHIEU_XUAT
(
    MaPX VARCHAR(10) NOT NULL,
    MaVT VARCHAR(10) NOT NULL,
    SoLuong DECIMAL(18,2) NOT NULL,

    CONSTRAINT PK_CT_PHIEU_XUAT PRIMARY KEY (MaPX, MaVT),

    CONSTRAINT FK_CT_XUAT_PHIEU_XUAT
        FOREIGN KEY (MaPX) REFERENCES PHIEU_XUAT(MaPX),

    CONSTRAINT FK_CT_XUAT_VAT_TU
        FOREIGN KEY (MaVT) REFERENCES VAT_TU(MaVT)
);

-- 12. Bảng phiếu chuyển kho
CREATE TABLE PHIEU_CHUYEN_KHO
(
    MaPCK VARCHAR(10) NOT NULL,
    MaKhoNguon VARCHAR(10) NOT NULL,
    MaKhoDich VARCHAR(10) NOT NULL,
    NgayChuyen DATETIME NOT NULL,
    NguoiLap VARCHAR(10) NOT NULL,
    GhiChu NVARCHAR(500),
    TrangThai VARCHAR(20) NOT NULL,

    CONSTRAINT PK_PHIEU_CHUYEN_KHO PRIMARY KEY (MaPCK),

    CONSTRAINT FK_CHUYEN_KHO_NGUON
        FOREIGN KEY (MaKhoNguon) REFERENCES KHO(MaKho),

    CONSTRAINT FK_CHUYEN_KHO_DICH
        FOREIGN KEY (MaKhoDich) REFERENCES KHO(MaKho),

    CONSTRAINT FK_CHUYEN_KHO_TAI_KHOAN
        FOREIGN KEY (NguoiLap) REFERENCES TAI_KHOAN(MaTK)
);

-- 13. Bảng chi tiết chuyển kho
CREATE TABLE CT_CHUYEN_KHO
(
    MaPCK VARCHAR(10) NOT NULL,
    MaVT VARCHAR(10) NOT NULL,
    SoLuong DECIMAL(18,2) NOT NULL,

    CONSTRAINT PK_CT_CHUYEN_KHO PRIMARY KEY (MaPCK, MaVT),

    CONSTRAINT FK_CT_CHUYEN_PHIEU_CHUYEN
        FOREIGN KEY (MaPCK) REFERENCES PHIEU_CHUYEN_KHO(MaPCK),

    CONSTRAINT FK_CT_CHUYEN_VAT_TU
        FOREIGN KEY (MaVT) REFERENCES VAT_TU(MaVT)
);

-- 14. Bảng phiếu điều chỉnh
CREATE TABLE PHIEU_DIEU_CHINH
(
    MaPDC VARCHAR(10) NOT NULL,
    MaKho VARCHAR(10) NOT NULL,
    NgayDieuChinh DATETIME NOT NULL,
    NguoiLap VARCHAR(10) NOT NULL,
    LyDo NVARCHAR(500) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,

    CONSTRAINT PK_PHIEU_DIEU_CHINH PRIMARY KEY (MaPDC),

    CONSTRAINT FK_DIEU_CHINH_KHO
        FOREIGN KEY (MaKho) REFERENCES KHO(MaKho),

    CONSTRAINT FK_DIEU_CHINH_TAI_KHOAN
        FOREIGN KEY (NguoiLap) REFERENCES TAI_KHOAN(MaTK)
);

-- 15. Bảng chi tiết điều chỉnh
CREATE TABLE CT_DIEU_CHINH
(
    MaPDC VARCHAR(10) NOT NULL,
    MaVT VARCHAR(10) NOT NULL,
    SoLuongTruoc DECIMAL(18,2) NOT NULL,
    SoLuongSau DECIMAL(18,2) NOT NULL,

    CONSTRAINT PK_CT_DIEU_CHINH PRIMARY KEY (MaPDC, MaVT),

    CONSTRAINT FK_CT_DIEU_CHINH_PHIEU
        FOREIGN KEY (MaPDC) REFERENCES PHIEU_DIEU_CHINH(MaPDC),

    CONSTRAINT FK_CT_DIEU_CHINH_VAT_TU
        FOREIGN KEY (MaVT) REFERENCES VAT_TU(MaVT)
);